// ***************************************************************
//  zfgw_pack
//  ---------------------------------------------------------------
//  This file was generated by zGen, don't modify manually.
//  Yongming Wang(wangym@gmail.com)
//  Copyright (C) 2026 - All Rights Reserved
// *****************************************************************

#include "zfgw_proto.h"
#include "zfgw_pack.h"
#include "zce/zds_schema.h"

using namespace zce;
using namespace zdp;
zfgw::FgwEndpoint zfgw::FgwEndpoint::_empty;
int zce::zdp::zds_pack(zce_byte* buf, int size, const zfgw::FgwEndpoint& _t, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    if (!zdp::is_empty_member(_t.host)) _struct_prefix |= 1ull << 0; 
    if (!zdp::is_empty_member(_t.port)) _struct_prefix |= 1ull << 1; 
    len = zds_pack_struct_header(buf, size, _struct_prefix, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_pack_builtin(buf, size,  _t.host, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 1)) {
        len = zds_pack_builtin(buf, size,  _t.port, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    return ret;
}

int zce::zdp::zds_unpack(zfgw::FgwEndpoint& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    len = zds_unpack_struct_header(_struct_prefix, buf, size, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_unpack_builtin(_t.host, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.host = {};
    };
    if (_struct_prefix & (1ull << 1)) {
        len = zds_unpack_builtin(_t.port, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.port = {};
    };
    _struct_prefix >>= 2;
    while (_struct_prefix != 0) {
        if (_struct_prefix & 1) {
            len = zds_unpack_skip(buf, size, ctx);
            CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
        }
        _struct_prefix >>= 1;
    };
    return ret;
}

zfgw::FgwChannelConfig zfgw::FgwChannelConfig::_empty;
int zce::zdp::zds_pack(zce_byte* buf, int size, const zfgw::FgwChannelConfig& _t, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    if (!zdp::is_empty_member(_t.channel_id)) _struct_prefix |= 1ull << 0; 
    if (!zdp::is_empty_member(_t.kind)) _struct_prefix |= 1ull << 1; 
    if (!zdp::is_empty_member(_t.remote)) _struct_prefix |= 1ull << 2; 
    if (!zdp::is_empty_member(_t.priority)) _struct_prefix |= 1ull << 3; 
    len = zds_pack_struct_header(buf, size, _struct_prefix, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_pack_builtin(buf, size,  _t.channel_id, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 1)) {
        len = zds_pack_builtin(buf, size,  _t.kind, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 2)) {
        len = zds_pack(buf, size, _t.remote, ctx, true);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 3)) {
        len = zds_pack_builtin(buf, size,  _t.priority, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    return ret;
}

int zce::zdp::zds_unpack(zfgw::FgwChannelConfig& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    len = zds_unpack_struct_header(_struct_prefix, buf, size, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_unpack_builtin(_t.channel_id, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.channel_id = {};
    };
    if (_struct_prefix & (1ull << 1)) {
        len = zds_unpack_builtin(_t.kind, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.kind = {};
    };
    if (_struct_prefix & (1ull << 2)) {
        len = zds_unpack(_t.remote, buf, size, ctx, true);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.remote = {};
    };
    if (_struct_prefix & (1ull << 3)) {
        len = zds_unpack_builtin(_t.priority, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.priority = {};
    };
    _struct_prefix >>= 4;
    while (_struct_prefix != 0) {
        if (_struct_prefix & 1) {
            len = zds_unpack_skip(buf, size, ctx);
            CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
        }
        _struct_prefix >>= 1;
    };
    return ret;
}

zfgw::FgwConfig zfgw::FgwConfig::_empty;
int zce::zdp::zds_pack(zce_byte* buf, int size, const zfgw::FgwConfig& _t, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    if (!zdp::is_empty_member(_t.role)) _struct_prefix |= 1ull << 0; 
    if (!zdp::is_empty_member(_t.ingress_id)) _struct_prefix |= 1ull << 1; 
    if (!zdp::is_empty_member(_t.inport_listen_port)) _struct_prefix |= 1ull << 2; 
    if (!zdp::is_empty_member(_t.outport_listen_host)) _struct_prefix |= 1ull << 3; 
    if (!zdp::is_empty_member(_t.outport_listen_port)) _struct_prefix |= 1ull << 4; 
    if (!zdp::is_empty_member(_t.egress_bind_ip)) _struct_prefix |= 1ull << 5; 
    if (!_t.channels.empty()) _struct_prefix |= 1ull << 6; 
    if (!zdp::is_empty_member(_t.segment_size)) _struct_prefix |= 1ull << 7; 
    if (!zdp::is_empty_member(_t.recv_window)) _struct_prefix |= 1ull << 8; 
    if (!zdp::is_empty_member(_t.heartbeat_interval)) _struct_prefix |= 1ull << 9; 
    if (!zdp::is_empty_member(_t.link_timeout)) _struct_prefix |= 1ull << 10; 
    if (!zdp::is_empty_member(_t.reconnect_max)) _struct_prefix |= 1ull << 11; 
    if (!zdp::is_empty_member(_t.multipath_mode)) _struct_prefix |= 1ull << 12; 
    if (!zdp::is_empty_member(_t.enable_crc)) _struct_prefix |= 1ull << 13; 
    len = zds_pack_struct_header(buf, size, _struct_prefix, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_pack_builtin(buf, size,  _t.role, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 1)) {
        len = zds_pack_builtin(buf, size,  _t.ingress_id, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 2)) {
        len = zds_pack_builtin(buf, size,  _t.inport_listen_port, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 3)) {
        len = zds_pack_builtin(buf, size,  _t.outport_listen_host, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 4)) {
        len = zds_pack_builtin(buf, size,  _t.outport_listen_port, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 5)) {
        len = zds_pack_builtin(buf, size,  _t.egress_bind_ip, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 6)) {
        len = zds_pack_array(buf, size, _t.channels, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    };
    if (_struct_prefix & (1ull << 7)) {
        len = zds_pack_builtin(buf, size,  _t.segment_size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 8)) {
        len = zds_pack_builtin(buf, size,  _t.recv_window, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 9)) {
        len = zds_pack_builtin(buf, size,  _t.heartbeat_interval, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 10)) {
        len = zds_pack_builtin(buf, size,  _t.link_timeout, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 11)) {
        len = zds_pack_builtin(buf, size,  _t.reconnect_max, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 12)) {
        len = zds_pack_builtin(buf, size,  _t.multipath_mode, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 13)) {
        len = zds_pack_builtin(buf, size,  _t.enable_crc, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    return ret;
}

int zce::zdp::zds_unpack(zfgw::FgwConfig& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    len = zds_unpack_struct_header(_struct_prefix, buf, size, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_unpack_builtin(_t.role, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.role = {};
    };
    if (_struct_prefix & (1ull << 1)) {
        len = zds_unpack_builtin(_t.ingress_id, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.ingress_id = {};
    };
    if (_struct_prefix & (1ull << 2)) {
        len = zds_unpack_builtin(_t.inport_listen_port, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.inport_listen_port = {};
    };
    if (_struct_prefix & (1ull << 3)) {
        len = zds_unpack_builtin(_t.outport_listen_host, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.outport_listen_host = {};
    };
    if (_struct_prefix & (1ull << 4)) {
        len = zds_unpack_builtin(_t.outport_listen_port, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.outport_listen_port = {};
    };
    if (_struct_prefix & (1ull << 5)) {
        len = zds_unpack_builtin(_t.egress_bind_ip, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.egress_bind_ip = {};
    };
    if (_struct_prefix & (1ull << 6)) {
        len = zds_unpack_array(_t.channels, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.channels = {};
    };
    if (_struct_prefix & (1ull << 7)) {
        len = zds_unpack_builtin(_t.segment_size, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.segment_size = {};
    };
    if (_struct_prefix & (1ull << 8)) {
        len = zds_unpack_builtin(_t.recv_window, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.recv_window = {};
    };
    if (_struct_prefix & (1ull << 9)) {
        len = zds_unpack_builtin(_t.heartbeat_interval, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.heartbeat_interval = {};
    };
    if (_struct_prefix & (1ull << 10)) {
        len = zds_unpack_builtin(_t.link_timeout, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.link_timeout = {};
    };
    if (_struct_prefix & (1ull << 11)) {
        len = zds_unpack_builtin(_t.reconnect_max, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.reconnect_max = {};
    };
    if (_struct_prefix & (1ull << 12)) {
        len = zds_unpack_builtin(_t.multipath_mode, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.multipath_mode = {};
    };
    if (_struct_prefix & (1ull << 13)) {
        len = zds_unpack_builtin(_t.enable_crc, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.enable_crc = {};
    };
    _struct_prefix >>= 14;
    while (_struct_prefix != 0) {
        if (_struct_prefix & 1) {
            len = zds_unpack_skip(buf, size, ctx);
            CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
        }
        _struct_prefix >>= 1;
    };
    return ret;
}

zfgw::FgwLinkQuality zfgw::FgwLinkQuality::_empty;
int zce::zdp::zds_pack(zce_byte* buf, int size, const zfgw::FgwLinkQuality& _t, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    if (!zdp::is_empty_member(_t.channel_id)) _struct_prefix |= 1ull << 0; 
    if (!zdp::is_empty_member(_t.connected)) _struct_prefix |= 1ull << 1; 
    if (!zdp::is_empty_member(_t.rtt_ms)) _struct_prefix |= 1ull << 2; 
    if (!zdp::is_empty_member(_t.loss_rate)) _struct_prefix |= 1ull << 3; 
    if (!zdp::is_empty_member(_t.bytes_sent)) _struct_prefix |= 1ull << 4; 
    if (!zdp::is_empty_member(_t.bytes_recv)) _struct_prefix |= 1ull << 5; 
    if (!zdp::is_empty_member(_t.send_segments)) _struct_prefix |= 1ull << 6; 
    if (!zdp::is_empty_member(_t.recv_segments)) _struct_prefix |= 1ull << 7; 
    if (!zdp::is_empty_member(_t.rexmit_segments)) _struct_prefix |= 1ull << 8; 
    len = zds_pack_struct_header(buf, size, _struct_prefix, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_pack_builtin(buf, size,  _t.channel_id, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 1)) {
        len = zds_pack_builtin(buf, size,  _t.connected, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 2)) {
        len = zds_pack_builtin(buf, size,  _t.rtt_ms, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 3)) {
        len = zds_pack_builtin(buf, size,  _t.loss_rate, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 4)) {
        len = zds_pack_builtin(buf, size,  _t.bytes_sent, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 5)) {
        len = zds_pack_builtin(buf, size,  _t.bytes_recv, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 6)) {
        len = zds_pack_builtin(buf, size,  _t.send_segments, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 7)) {
        len = zds_pack_builtin(buf, size,  _t.recv_segments, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 8)) {
        len = zds_pack_builtin(buf, size,  _t.rexmit_segments, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    return ret;
}

int zce::zdp::zds_unpack(zfgw::FgwLinkQuality& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    len = zds_unpack_struct_header(_struct_prefix, buf, size, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_unpack_builtin(_t.channel_id, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.channel_id = {};
    };
    if (_struct_prefix & (1ull << 1)) {
        len = zds_unpack_builtin(_t.connected, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.connected = {};
    };
    if (_struct_prefix & (1ull << 2)) {
        len = zds_unpack_builtin(_t.rtt_ms, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.rtt_ms = {};
    };
    if (_struct_prefix & (1ull << 3)) {
        len = zds_unpack_builtin(_t.loss_rate, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.loss_rate = {};
    };
    if (_struct_prefix & (1ull << 4)) {
        len = zds_unpack_builtin(_t.bytes_sent, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.bytes_sent = {};
    };
    if (_struct_prefix & (1ull << 5)) {
        len = zds_unpack_builtin(_t.bytes_recv, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.bytes_recv = {};
    };
    if (_struct_prefix & (1ull << 6)) {
        len = zds_unpack_builtin(_t.send_segments, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.send_segments = {};
    };
    if (_struct_prefix & (1ull << 7)) {
        len = zds_unpack_builtin(_t.recv_segments, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.recv_segments = {};
    };
    if (_struct_prefix & (1ull << 8)) {
        len = zds_unpack_builtin(_t.rexmit_segments, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.rexmit_segments = {};
    };
    _struct_prefix >>= 9;
    while (_struct_prefix != 0) {
        if (_struct_prefix & 1) {
            len = zds_unpack_skip(buf, size, ctx);
            CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
        }
        _struct_prefix >>= 1;
    };
    return ret;
}

zfgw::FgwSessionStat zfgw::FgwSessionStat::_empty;
int zce::zdp::zds_pack(zce_byte* buf, int size, const zfgw::FgwSessionStat& _t, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    if (!zdp::is_empty_member(_t.session_id)) _struct_prefix |= 1ull << 0; 
    if (!zdp::is_empty_member(_t.ingress_id)) _struct_prefix |= 1ull << 1; 
    if (!zdp::is_empty_member(_t.client_addr)) _struct_prefix |= 1ull << 2; 
    if (!zdp::is_empty_member(_t.target_addr)) _struct_prefix |= 1ull << 3; 
    if (!zdp::is_empty_member(_t.bytes_sent)) _struct_prefix |= 1ull << 4; 
    if (!zdp::is_empty_member(_t.bytes_recv)) _struct_prefix |= 1ull << 5; 
    if (!zdp::is_empty_member(_t.open_timestamp)) _struct_prefix |= 1ull << 6; 
    len = zds_pack_struct_header(buf, size, _struct_prefix, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_pack_builtin(buf, size,  _t.session_id, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 1)) {
        len = zds_pack_builtin(buf, size,  _t.ingress_id, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 2)) {
        len = zds_pack_builtin(buf, size,  _t.client_addr, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 3)) {
        len = zds_pack_builtin(buf, size,  _t.target_addr, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 4)) {
        len = zds_pack_builtin(buf, size,  _t.bytes_sent, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 5)) {
        len = zds_pack_builtin(buf, size,  _t.bytes_recv, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 6)) {
        len = zds_pack_builtin(buf, size,  _t.open_timestamp, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    return ret;
}

int zce::zdp::zds_unpack(zfgw::FgwSessionStat& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    len = zds_unpack_struct_header(_struct_prefix, buf, size, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_unpack_builtin(_t.session_id, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.session_id = {};
    };
    if (_struct_prefix & (1ull << 1)) {
        len = zds_unpack_builtin(_t.ingress_id, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.ingress_id = {};
    };
    if (_struct_prefix & (1ull << 2)) {
        len = zds_unpack_builtin(_t.client_addr, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.client_addr = {};
    };
    if (_struct_prefix & (1ull << 3)) {
        len = zds_unpack_builtin(_t.target_addr, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.target_addr = {};
    };
    if (_struct_prefix & (1ull << 4)) {
        len = zds_unpack_builtin(_t.bytes_sent, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.bytes_sent = {};
    };
    if (_struct_prefix & (1ull << 5)) {
        len = zds_unpack_builtin(_t.bytes_recv, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.bytes_recv = {};
    };
    if (_struct_prefix & (1ull << 6)) {
        len = zds_unpack_builtin(_t.open_timestamp, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.open_timestamp = {};
    };
    _struct_prefix >>= 7;
    while (_struct_prefix != 0) {
        if (_struct_prefix & 1) {
            len = zds_unpack_skip(buf, size, ctx);
            CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
        }
        _struct_prefix >>= 1;
    };
    return ret;
}

zfgw::FgwStatus zfgw::FgwStatus::_empty;
int zce::zdp::zds_pack(zce_byte* buf, int size, const zfgw::FgwStatus& _t, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    if (!zdp::is_empty_member(_t.running)) _struct_prefix |= 1ull << 0; 
    if (!zdp::is_empty_member(_t.role)) _struct_prefix |= 1ull << 1; 
    if (!zdp::is_empty_member(_t.session_count)) _struct_prefix |= 1ull << 2; 
    if (!_t.links.empty()) _struct_prefix |= 1ull << 3; 
    if (!_t.sessions.empty()) _struct_prefix |= 1ull << 4; 
    len = zds_pack_struct_header(buf, size, _struct_prefix, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_pack_builtin(buf, size,  _t.running, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 1)) {
        len = zds_pack_builtin(buf, size,  _t.role, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 2)) {
        len = zds_pack_builtin(buf, size,  _t.session_count, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 3)) {
        len = zds_pack_array(buf, size, _t.links, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    };
    if (_struct_prefix & (1ull << 4)) {
        len = zds_pack_array(buf, size, _t.sessions, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    };
    return ret;
}

int zce::zdp::zds_unpack(zfgw::FgwStatus& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    len = zds_unpack_struct_header(_struct_prefix, buf, size, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_unpack_builtin(_t.running, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.running = {};
    };
    if (_struct_prefix & (1ull << 1)) {
        len = zds_unpack_builtin(_t.role, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.role = {};
    };
    if (_struct_prefix & (1ull << 2)) {
        len = zds_unpack_builtin(_t.session_count, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.session_count = {};
    };
    if (_struct_prefix & (1ull << 3)) {
        len = zds_unpack_array(_t.links, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.links = {};
    };
    if (_struct_prefix & (1ull << 4)) {
        len = zds_unpack_array(_t.sessions, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.sessions = {};
    };
    _struct_prefix >>= 5;
    while (_struct_prefix != 0) {
        if (_struct_prefix & 1) {
            len = zds_unpack_skip(buf, size, ctx);
            CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
        }
        _struct_prefix >>= 1;
    };
    return ret;
}

zfgw::FgwEmpty zfgw::FgwEmpty::_empty;
int zce::zdp::zds_pack(zce_byte* buf, int size, const zfgw::FgwEmpty& _t, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    if (!zdp::is_empty_member(_t._placeholder)) _struct_prefix |= 1ull << 0; 
    len = zds_pack_struct_header(buf, size, _struct_prefix, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_pack_builtin(buf, size,  _t._placeholder, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    return ret;
}

int zce::zdp::zds_unpack(zfgw::FgwEmpty& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    len = zds_unpack_struct_header(_struct_prefix, buf, size, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_unpack_builtin(_t._placeholder, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t._placeholder = {};
    };
    _struct_prefix >>= 1;
    while (_struct_prefix != 0) {
        if (_struct_prefix & 1) {
            len = zds_unpack_skip(buf, size, ctx);
            CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
        }
        _struct_prefix >>= 1;
    };
    return ret;
}

zfgw::FgwStartRequest zfgw::FgwStartRequest::_empty;
int zce::zdp::zds_pack(zce_byte* buf, int size, const zfgw::FgwStartRequest& _t, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    if (!zdp::is_empty_member(_t.force_restart)) _struct_prefix |= 1ull << 0; 
    len = zds_pack_struct_header(buf, size, _struct_prefix, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_pack_builtin(buf, size,  _t.force_restart, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    return ret;
}

int zce::zdp::zds_unpack(zfgw::FgwStartRequest& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    len = zds_unpack_struct_header(_struct_prefix, buf, size, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_unpack_builtin(_t.force_restart, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.force_restart = {};
    };
    _struct_prefix >>= 1;
    while (_struct_prefix != 0) {
        if (_struct_prefix & 1) {
            len = zds_unpack_skip(buf, size, ctx);
            CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
        }
        _struct_prefix >>= 1;
    };
    return ret;
}

zfgw::FgwStartResult zfgw::FgwStartResult::_empty;
int zce::zdp::zds_pack(zce_byte* buf, int size, const zfgw::FgwStartResult& _t, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    if (!zdp::is_empty_member(_t.errcode)) _struct_prefix |= 1ull << 0; 
    if (!zdp::is_empty_member(_t.message)) _struct_prefix |= 1ull << 1; 
    len = zds_pack_struct_header(buf, size, _struct_prefix, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_pack_builtin(buf, size,  _t.errcode, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 1)) {
        len = zds_pack_builtin(buf, size,  _t.message, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    return ret;
}

int zce::zdp::zds_unpack(zfgw::FgwStartResult& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    len = zds_unpack_struct_header(_struct_prefix, buf, size, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_unpack_builtin(_t.errcode, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.errcode = {};
    };
    if (_struct_prefix & (1ull << 1)) {
        len = zds_unpack_builtin(_t.message, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.message = {};
    };
    _struct_prefix >>= 2;
    while (_struct_prefix != 0) {
        if (_struct_prefix & 1) {
            len = zds_unpack_skip(buf, size, ctx);
            CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
        }
        _struct_prefix >>= 1;
    };
    return ret;
}

zfgw::FgwAddChannelRequest zfgw::FgwAddChannelRequest::_empty;
int zce::zdp::zds_pack(zce_byte* buf, int size, const zfgw::FgwAddChannelRequest& _t, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    if (!zdp::is_empty_member(_t.channel)) _struct_prefix |= 1ull << 0; 
    len = zds_pack_struct_header(buf, size, _struct_prefix, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_pack(buf, size, _t.channel, ctx, true);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    return ret;
}

int zce::zdp::zds_unpack(zfgw::FgwAddChannelRequest& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    len = zds_unpack_struct_header(_struct_prefix, buf, size, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_unpack(_t.channel, buf, size, ctx, true);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.channel = {};
    };
    _struct_prefix >>= 1;
    while (_struct_prefix != 0) {
        if (_struct_prefix & 1) {
            len = zds_unpack_skip(buf, size, ctx);
            CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
        }
        _struct_prefix >>= 1;
    };
    return ret;
}

zfgw::FgwRemoveChannelRequest zfgw::FgwRemoveChannelRequest::_empty;
int zce::zdp::zds_pack(zce_byte* buf, int size, const zfgw::FgwRemoveChannelRequest& _t, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    if (!zdp::is_empty_member(_t.channel_id)) _struct_prefix |= 1ull << 0; 
    len = zds_pack_struct_header(buf, size, _struct_prefix, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_pack_builtin(buf, size,  _t.channel_id, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    return ret;
}

int zce::zdp::zds_unpack(zfgw::FgwRemoveChannelRequest& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    len = zds_unpack_struct_header(_struct_prefix, buf, size, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_unpack_builtin(_t.channel_id, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.channel_id = {};
    };
    _struct_prefix >>= 1;
    while (_struct_prefix != 0) {
        if (_struct_prefix & 1) {
            len = zds_unpack_skip(buf, size, ctx);
            CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
        }
        _struct_prefix >>= 1;
    };
    return ret;
}

zfgw::FgwSetConfigRequest zfgw::FgwSetConfigRequest::_empty;
int zce::zdp::zds_pack(zce_byte* buf, int size, const zfgw::FgwSetConfigRequest& _t, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    if (!zdp::is_empty_member(_t.config)) _struct_prefix |= 1ull << 0; 
    len = zds_pack_struct_header(buf, size, _struct_prefix, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_pack(buf, size, _t.config, ctx, true);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    return ret;
}

int zce::zdp::zds_unpack(zfgw::FgwSetConfigRequest& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    len = zds_unpack_struct_header(_struct_prefix, buf, size, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_unpack(_t.config, buf, size, ctx, true);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.config = {};
    };
    _struct_prefix >>= 1;
    while (_struct_prefix != 0) {
        if (_struct_prefix & 1) {
            len = zds_unpack_skip(buf, size, ctx);
            CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
        }
        _struct_prefix >>= 1;
    };
    return ret;
}

zfgw::FgwHello zfgw::FgwHello::_empty;
int zce::zdp::zds_pack(zce_byte* buf, int size, const zfgw::FgwHello& _t, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    if (!zdp::is_empty_member(_t.proto_version)) _struct_prefix |= 1ull << 0; 
    if (!zdp::is_empty_member(_t.role)) _struct_prefix |= 1ull << 1; 
    if (!zdp::is_empty_member(_t.ingress_id)) _struct_prefix |= 1ull << 2; 
    if (!zdp::is_empty_member(_t.outport_id)) _struct_prefix |= 1ull << 3; 
    if (!zdp::is_empty_member(_t.channel_id)) _struct_prefix |= 1ull << 4; 
    len = zds_pack_struct_header(buf, size, _struct_prefix, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_pack_builtin(buf, size,  _t.proto_version, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 1)) {
        len = zds_pack_builtin(buf, size,  _t.role, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 2)) {
        len = zds_pack_builtin(buf, size,  _t.ingress_id, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 3)) {
        len = zds_pack_builtin(buf, size,  _t.outport_id, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 4)) {
        len = zds_pack_builtin(buf, size,  _t.channel_id, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    return ret;
}

int zce::zdp::zds_unpack(zfgw::FgwHello& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    len = zds_unpack_struct_header(_struct_prefix, buf, size, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_unpack_builtin(_t.proto_version, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.proto_version = {};
    };
    if (_struct_prefix & (1ull << 1)) {
        len = zds_unpack_builtin(_t.role, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.role = {};
    };
    if (_struct_prefix & (1ull << 2)) {
        len = zds_unpack_builtin(_t.ingress_id, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.ingress_id = {};
    };
    if (_struct_prefix & (1ull << 3)) {
        len = zds_unpack_builtin(_t.outport_id, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.outport_id = {};
    };
    if (_struct_prefix & (1ull << 4)) {
        len = zds_unpack_builtin(_t.channel_id, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.channel_id = {};
    };
    _struct_prefix >>= 5;
    while (_struct_prefix != 0) {
        if (_struct_prefix & 1) {
            len = zds_unpack_skip(buf, size, ctx);
            CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
        }
        _struct_prefix >>= 1;
    };
    return ret;
}

zfgw::FgwLinkFeedback zfgw::FgwLinkFeedback::_empty;
int zce::zdp::zds_pack(zce_byte* buf, int size, const zfgw::FgwLinkFeedback& _t, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    if (!zdp::is_empty_member(_t.decision_epoch)) _struct_prefix |= 1ull << 0; 
    if (!zdp::is_empty_member(_t.recommended_primary)) _struct_prefix |= 1ull << 1; 
    if (!zdp::is_empty_member(_t.alive_bitmap)) _struct_prefix |= 1ull << 2; 
    if (!zdp::is_empty_member(_t.highest_seq)) _struct_prefix |= 1ull << 3; 
    len = zds_pack_struct_header(buf, size, _struct_prefix, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_pack_builtin(buf, size,  _t.decision_epoch, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 1)) {
        len = zds_pack_builtin(buf, size,  _t.recommended_primary, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 2)) {
        len = zds_pack_builtin(buf, size,  _t.alive_bitmap, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    if (_struct_prefix & (1ull << 3)) {
        len = zds_pack_builtin(buf, size,  _t.highest_seq, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    };
    return ret;
}

int zce::zdp::zds_unpack(zfgw::FgwLinkFeedback& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix)
{
    int len = 0, ret = 0;
    zce_uint64 _struct_prefix = 0;
    len = zds_unpack_struct_header(_struct_prefix, buf, size, ctx, has_prefix);
    CHECKLEN_MOVEBUF_ADDRET_DECSIZE;

    if (_struct_prefix & (1ull << 0)) {
        len = zds_unpack_builtin(_t.decision_epoch, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.decision_epoch = {};
    };
    if (_struct_prefix & (1ull << 1)) {
        len = zds_unpack_builtin(_t.recommended_primary, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.recommended_primary = {};
    };
    if (_struct_prefix & (1ull << 2)) {
        len = zds_unpack_builtin(_t.alive_bitmap, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.alive_bitmap = {};
    };
    if (_struct_prefix & (1ull << 3)) {
        len = zds_unpack_builtin(_t.highest_seq, buf, size, ctx);
        CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
    } else {
        _t.highest_seq = {};
    };
    _struct_prefix >>= 4;
    while (_struct_prefix != 0) {
        if (_struct_prefix & 1) {
            len = zds_unpack_skip(buf, size, ctx);
            CHECKLEN_MOVEBUF_ADDRET_DECSIZE;
        }
        _struct_prefix >>= 1;
    };
    return ret;
}

