// ***************************************************************
//  zfgw_pack
//  ---------------------------------------------------------------
//  This file was generated by zGen, don't modify manually.
//  Yongming Wang(wangym@gmail.com)
//  Copyright (C) 2026 - All Rights Reserved
// *****************************************************************

#pragma once

#include "zfgw_proto.h"
#include "zfgw_pack.h"
#include <zce/zce_config.h>
#include <zce/zce_object.h>
#include <zce/zce_types.h>
#include <zce/zce_dblock.h>
#include <zce/zce_any.h>
namespace zce
{
    namespace zdp
    {
        int zds_pack(zce_byte* buf, int size, const zfgw::FgwEndpoint& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zfgw::FgwEndpoint& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zfgw::FgwChannelConfig& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zfgw::FgwChannelConfig& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zfgw::FgwConfig& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zfgw::FgwConfig& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zfgw::FgwLinkQuality& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zfgw::FgwLinkQuality& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zfgw::FgwSessionStat& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zfgw::FgwSessionStat& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zfgw::FgwStatus& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zfgw::FgwStatus& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zfgw::FgwEmpty& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zfgw::FgwEmpty& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zfgw::FgwStartRequest& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zfgw::FgwStartRequest& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zfgw::FgwStartResult& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zfgw::FgwStartResult& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zfgw::FgwAddChannelRequest& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zfgw::FgwAddChannelRequest& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zfgw::FgwRemoveChannelRequest& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zfgw::FgwRemoveChannelRequest& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zfgw::FgwSetConfigRequest& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zfgw::FgwSetConfigRequest& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zfgw::FgwHello& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zfgw::FgwHello& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
        int zds_pack(zce_byte* buf, int size, const zfgw::FgwLinkFeedback& _t, zds_context_t* ctx, bool has_prefix);
        int zds_unpack(zfgw::FgwLinkFeedback& _t, const zce_byte* buf, int size, zds_context_t* ctx, bool has_prefix);
    } //namespace zdp
} //namespace zce
