// ***************************************************************
//  zfgw_proto
//  ---------------------------------------------------------------
//  This file was generated by zGen, don't modify manually.
//  Yongming Wang(wangym@gmail.com)
//  Copyright (C) 2026 - All Rights Reserved
// *****************************************************************

#pragma once

#include <zce/zce_config.h>
#include <zce/zce_object.h>
#include <zce/zce_types.h>
#include <zce/zce_dblock.h>
#include <zce/zce_any.h>
namespace zfgw
{
    struct FgwEndpoint
    {
        static FgwEndpoint _empty;
        bool operator==(const FgwEndpoint& _t) const noexcept
        {
            if (host != _t.host) return false;
            if (port != _t.port) return false;
            return true;
        }

        zce_astring    host/* IPv4/IPv6 literal or DNS name */;
        zce_uint16    port/* TCP or UDP port */;
    };
    struct FgwChannelConfig
    {
        static FgwChannelConfig _empty;
        bool operator==(const FgwChannelConfig& _t) const noexcept
        {
            if (channel_id != _t.channel_id) return false;
            if (kind != _t.kind) return false;
            if (!(remote == _t.remote)) return false;
            if (priority != _t.priority) return false;
            return true;
        }

        zce_uint32    channel_id/* unique id inside a VM */;
        zce_byte    kind/* 0 = TCP, 1 = UTP */;
        FgwEndpoint    remote/* remote endpoint to dial */;
        zce_uint32    priority = 100/* larger = more preferred */;
    };
    struct FgwConfig
    {
        static FgwConfig _empty;
        bool operator==(const FgwConfig& _t) const noexcept
        {
            if (role != _t.role) return false;
            if (ingress_id != _t.ingress_id) return false;
            if (inport_listen_port != _t.inport_listen_port) return false;
            if (outport_listen_host != _t.outport_listen_host) return false;
            if (outport_listen_port != _t.outport_listen_port) return false;
            if (!(channels == _t.channels)) return false;
            if (segment_size != _t.segment_size) return false;
            if (recv_window != _t.recv_window) return false;
            if (heartbeat_interval != _t.heartbeat_interval) return false;
            if (link_timeout != _t.link_timeout) return false;
            if (reconnect_max != _t.reconnect_max) return false;
            if (multipath_mode != _t.multipath_mode) return false;
            if (enable_crc != _t.enable_crc) return false;
            if (route_outport_id != _t.route_outport_id) return false;
            return true;
        }

        zce_byte    role/* 0 = inport (client), 1 = outport (server) */;
        zce_uint32    ingress_id = 0/* unique Inport id on shared multipath links */;
        zce_uint16    inport_listen_port = 1080/* SOCKS5 local listen port on Inport */;
        zce_astring    outport_listen_host/* listen ip for Outport side */;
        zce_uint16    outport_listen_port = 0/* listen port for Outport side */;
        std::vector<zfgw::FgwChannelConfig> channels/* pre-configured channels */;
        zce_uint16    segment_size = 1200/* payload size per segment */;
        zce_uint16    recv_window = 1024/* receive window size (segments) */;
        zce_uint16    heartbeat_interval = 5/* seconds */;
        zce_uint16    link_timeout = 15/* seconds */;
        zce_uint16    reconnect_max = 60/* seconds */;
        zce_byte    multipath_mode = 2/* 0 = best, 1 = all, 2 = weighted */;
        zce_byte    enable_crc = 1/* bool */;
        zce_uint32    route_outport_id = 0;
    };
    struct FgwLinkQuality
    {
        static FgwLinkQuality _empty;
        bool operator==(const FgwLinkQuality& _t) const noexcept
        {
            if (channel_id != _t.channel_id) return false;
            if (connected != _t.connected) return false;
            if (rtt_ms != _t.rtt_ms) return false;
            if (loss_rate != _t.loss_rate) return false;
            if (bytes_sent != _t.bytes_sent) return false;
            if (bytes_recv != _t.bytes_recv) return false;
            if (send_segments != _t.send_segments) return false;
            if (recv_segments != _t.recv_segments) return false;
            if (rexmit_segments != _t.rexmit_segments) return false;
            return true;
        }

        zce_uint32    channel_id;
        zce_byte    connected/* bool */;
        zce_uint32    rtt_ms;
        zce_double    loss_rate/* 0.0 ~ 1.0 */;
        zce_uint64    bytes_sent;
        zce_uint64    bytes_recv;
        zce_uint32    send_segments;
        zce_uint32    recv_segments;
        zce_uint32    rexmit_segments;
    };
    struct FgwSessionStat
    {
        static FgwSessionStat _empty;
        bool operator==(const FgwSessionStat& _t) const noexcept
        {
            if (session_id != _t.session_id) return false;
            if (ingress_id != _t.ingress_id) return false;
            if (client_addr != _t.client_addr) return false;
            if (target_addr != _t.target_addr) return false;
            if (bytes_sent != _t.bytes_sent) return false;
            if (bytes_recv != _t.bytes_recv) return false;
            if (open_timestamp != _t.open_timestamp) return false;
            return true;
        }

        zce_uint32    session_id;
        zce_uint32    ingress_id = 0/* Inport id (client side) for this session */;
        zce_astring    client_addr/* client IP:Port */;
        zce_astring    target_addr/* SOCKS5 target (on outport only) */;
        zce_uint64    bytes_sent;
        zce_uint64    bytes_recv;
        zce_uint32    open_timestamp/* seconds since epoch */;
    };
    struct FgwStatus
    {
        static FgwStatus _empty;
        bool operator==(const FgwStatus& _t) const noexcept
        {
            if (running != _t.running) return false;
            if (role != _t.role) return false;
            if (session_count != _t.session_count) return false;
            if (!(links == _t.links)) return false;
            if (!(sessions == _t.sessions)) return false;
            return true;
        }

        zce_byte    running/* bool */;
        zce_byte    role/* mirror of config.role */;
        zce_uint32    session_count;
        std::vector<zfgw::FgwLinkQuality> links;
        std::vector<zfgw::FgwSessionStat> sessions;
    };
    struct FgwEmpty
    {
        static FgwEmpty _empty;
        bool operator==(const FgwEmpty& _t) const noexcept
        {
            if (_placeholder != _t._placeholder) return false;
            return true;
        }

        zce_byte    _placeholder = 0;
    };
    struct FgwStartRequest
    {
        static FgwStartRequest _empty;
        bool operator==(const FgwStartRequest& _t) const noexcept
        {
            if (force_restart != _t.force_restart) return false;
            return true;
        }

        zce_byte    force_restart = 0/* bool */;
    };
    struct FgwStartResult
    {
        static FgwStartResult _empty;
        bool operator==(const FgwStartResult& _t) const noexcept
        {
            if (errcode != _t.errcode) return false;
            if (message != _t.message) return false;
            return true;
        }

        zce_int32    errcode;
        zce_astring    message;
    };
    struct FgwAddChannelRequest
    {
        static FgwAddChannelRequest _empty;
        bool operator==(const FgwAddChannelRequest& _t) const noexcept
        {
            if (!(channel == _t.channel)) return false;
            return true;
        }

        FgwChannelConfig    channel;
    };
    struct FgwRemoveChannelRequest
    {
        static FgwRemoveChannelRequest _empty;
        bool operator==(const FgwRemoveChannelRequest& _t) const noexcept
        {
            if (channel_id != _t.channel_id) return false;
            return true;
        }

        zce_uint32    channel_id;
    };
    struct FgwSetConfigRequest
    {
        static FgwSetConfigRequest _empty;
        bool operator==(const FgwSetConfigRequest& _t) const noexcept
        {
            if (!(config == _t.config)) return false;
            return true;
        }

        FgwConfig    config;
    };
    struct FgwHello
    {
        static FgwHello _empty;
        bool operator==(const FgwHello& _t) const noexcept
        {
            if (proto_version != _t.proto_version) return false;
            if (role != _t.role) return false;
            if (ingress_id != _t.ingress_id) return false;
            if (outport_id != _t.outport_id) return false;
            if (channel_id != _t.channel_id) return false;
            if (generation != _t.generation) return false;
            return true;
        }

        zce_uint16    proto_version = 2/* wire protocol version */;
        zce_byte    role/* sender role: 0=inport,1=outport,2=transit */;
        zce_uint32    ingress_id/* sender ingress id (reverse-routing key) */;
        zce_uint32    outport_id/* desired egress id (forward-routing key), 0 if N/A */;
        zce_uint32    channel_id/* sender-local channel id */;
        zce_uint32    generation/* sender process incarnation nonce; a change
        means the peer restarted -> reset epoch */;
    };
    struct FgwLinkFeedback
    {
        static FgwLinkFeedback _empty;
        bool operator==(const FgwLinkFeedback& _t) const noexcept
        {
            if (decision_epoch != _t.decision_epoch) return false;
            if (recommended_primary != _t.recommended_primary) return false;
            if (alive_bitmap != _t.alive_bitmap) return false;
            if (highest_seq != _t.highest_seq) return false;
            return true;
        }

        zce_uint32    decision_epoch/* monotonically increasing */;
        zce_uint32    recommended_primary/* recommended primary channel id */;
        zce_uint32    alive_bitmap/* per-channel recent-liveness bitmap */;
        zce_uint32    highest_seq/* highest contiguous seq received */;
    };
} //namespace zfgw
